Repository azooKey/AzooKeyKanaKanjiConverter, pull requests merged in 2024-03, with the labels that each got.

#56 [Fix] Swift 5.10でのビルドエラーを修正
  Sources/KanaKanjiConverterModule/LOUDS/LOUDS.swift
  Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ExperimentalTests/InputGraph/InputGraphProtocol.swift
Labels: bug

#59 [Docs] 開発ガイドを追加
  Docs/README.md
  Docs/development_guide.md
  README.md
Labels: documentation

#60 [Docs] Update failures.md
  Docs/failures.md
Labels: bug

#64 [Experimental] 実験的実装から不要なものを削除し、lintを適用
  Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ExperimentalTests/InputGraph/ConvertGraph.swift
  Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ExperimentalTests/InputGraph/CorrectGraph.swift
  Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ExperimentalTests/InputGraph/CorrectPrefixTree.swift
  Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ExperimentalTests/InputGraph/InputGraph.swift
  Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ExperimentalTests/InputGraph/InputGraphComponents.swift
  Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ExperimentalTests/InputGraph/InputGraphTests.swift
  Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ExperimentalTests/InputGraph/Iota.swift
  Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ExperimentalTests/InputGraph/LookupGraphTests.swift
  Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ExperimentalTests/InputGraph/ReplaceSuffixTree.swift
Labels: refactoring

#72 Update Swift image version to 5.10
  .devcontainer/devcontainer.json
Labels: tools

#73 [Refactoring] SwiftUtilsの不必要なAPIを削除する
  Sources/SwiftUtils/AppVersion.swift
  Sources/SwiftUtils/ArrayUtils.swift
  Sources/SwiftUtils/CodableSupport.swift
  Sources/SwiftUtils/StringUtils.swift
  Sources/SwiftUtils/UserDefaultsManager.swift
  Sources/SwiftUtils/WithMutableValue.swift
  Tests/SwiftUtilsTests/AppVersionTests.swift
  Tests/SwiftUtilsTests/StringExtensionTests.swift
Labels: refactoring
