Repository azooKey/AzooKeyKanaKanjiConverter, pull requests merged in 2025-07, with the labels that each got.

#216 refactor: 最適化に寄与しないキャッシュ活用のspecializationを削除
  Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/FullInputProcessing.swift
  Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/FullInputProcessingWithPrefixConstraint.swift
  Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/PredictionProcessing.swift
  Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/PrefixCompletionProcessing.swift
  Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/SuffixDeletionProcessing.swift
  Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/SuffixReplacementProcessing.swift
  Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/UnchangedInputProcessing.swift
  Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/added_last_1_character.swift
  Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/added_last_n_character.swift
  Sources/KanaKanjiConverterModule/ConverterAPI/KanaKanjiConverter.swift
  Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ConverterTests/ConverterTests.swift
Labels: refactoring

#217 fix: Kana2Kanjiのインスタンスを引数なしで作成してしまうバグを修正
  Sources/KanaKanjiConverterModule/ConverterAPI/KanaKanjiConverter.swift
Labels: bug

#222 refactor: `Lattice`の`nodes`を外部からアクセス不可能にし、内部実装を変更しやすくした
  Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/FullInputProcessing.swift
  Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/FullInputProcessingWithPrefixConstraint.swift
  Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/PrefixCompletionProcessing.swift
  Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/SuffixReplacementProcessing.swift
  Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/UnchangedInputProcessing.swift
  Sources/KanaKanjiConverterModule/ConversionAlgorithms/Lattice.swift
  Sources/KanaKanjiConverterModule/ConversionAlgorithms/Zenzai/zenzai.swift
  Sources/KanaKanjiConverterModule/ConverterAPI/KanaKanjiConverter.swift
Labels: refactoring

#224 refactor: 特定のローマ字かな変換テーブルを前提にした複雑な境界チェックを廃止する
  Sources/KanaKanjiConverterModule/DictionaryManagement/TypoCorrection.swift
  Sources/KanaKanjiConverterModule/InputManagement/ComposingText.swift
  Tests/KanaKanjiConverterModuleTests/ComposingTextTests.swift
  Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/DicdataStoreTests/DicdataStoreTests.swift
Labels: refactoring

#227 feat: `.mapped(id)`を新たな入力スタイルとして導入し、カスタムローマ字かな変換テーブルに対応
  Sources/KanaKanjiConverterModule/ConversionAlgorithms/Prediction.swift
  Sources/KanaKanjiConverterModule/ConverterAPI/KanaKanjiConverter.swift
  Sources/KanaKanjiConverterModule/DictionaryManagement/DicdataStore.swift
  Sources/KanaKanjiConverterModule/DictionaryManagement/TypoCorrection.swift
  Sources/KanaKanjiConverterModule/InputManagement/ComposingText.swift
  Sources/KanaKanjiConverterModule/InputManagement/InputStyle.swift
  Sources/KanaKanjiConverterModule/InputManagement/InputStyleManager.swift
  Sources/KanaKanjiConverterModule/InputManagement/InputTableID.swift
  Sources/KanaKanjiConverterModule/InputManagement/Roman2Kana.swift
  Sources/KanaKanjiConverterModule/InputManagement/Roman2KanaMaps.swift
  Sources/KanaKanjiConverterModule/InputManagement/States.swift
  Sources/SwiftUtils/CharacterUtils.swift
  Tests/KanaKanjiConverterModuleTests/ComposingTextTests.swift
  Tests/KanaKanjiConverterModuleTests/InputStyleManagerTests.swift
  Tests/KanaKanjiConverterModuleTests/Roman2KanaTests.swift
  Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ConverterTests/ConverterTests.swift
  Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/DicdataStoreTests/DicdataStoreTests.swift
  Tests/SwiftUtilsTests/CharacterUtilsTests.swift
Labels: enhancement
